# -*- coding: utf-8 -*-
"""MLDL_Lab1.ipynb

Automatically generated by Colab.

Original file is located at
"""

# from google.colab import drive
# drive.mount('/content/drive')

import itertools
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings(action='ignore')

"""##0. Numpy & Pandas basics

### Numpy arrays
"""

import numpy as np

"""- np.array()
- np.arange()
- np.zeros()
- np.ones()
- np.eye()

"""

a = [[1,2,3], [4,5,6]] #generate from list
b = np.array(a)
print(b)

print(f"number of rows : {b.ndim}")
print(f"number of columns : {b.shape[1]}")

print(np.arange(10))
print(np.arange(5,10))

print(np.zeros((2,2))) #2x2 zero matrix

print(np.ones((2,3))) #2x3 unit matrix

print(np.eye(3)) #3x3 identity matrix

"""## Handling arrays
- reshape
- transpose
- slicing
- np.stack / np.concatenate
"""

a = np.arange(10)
print(a.shape)

b = a.reshape((2, -1)) # 나머지 값 알아서 맞춰줘! == -1 사용
print(b.shape)
print(b)

c = b.transpose()
print(c.shape)
print(c)

print(b[:2, :2])

d = b[:2, :2].copy()
d[0] = 10
b

print(b[1:, :])

#hstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.hstack([a, b])

np.concatenate((a,b), axis=0)

#vstack
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.vstack([a, b])

"""## Numpy Operations
- +,-,*,/
- broadcasting
- add(), substract(), multiply(), divide()
- dot(), sum(), prod(), np.linalg.inv()
"""

a = np.arange(1,4)
b = np.arange(4,7)
a,b

print(a.shape)
print(b.shape)

# element-wise addition
c = a+b
print(c)

c = a * b
c

#broadcasting
print(a * np.array([1,2,3]))
print(a * 3)

c = np.dot(a,b)
print(c)

s = np.sum(a) # a = [1 2 3]
print(s)

s = np.prod(a) # a = [1 2 3]
print(s)

# axis designated operation
a = np.array([[-1,2,3], [3,4,8]])
print(a)
print()
print(f"sum by row: {a.sum(axis = 0)}") #sum by row
print(f"sum by column: {a.sum(axis = 1)}") #sum by column

x = np.array([[1,2], [3,4],[5,6]])
y = np.array([[6, 23], [-1,7],[8,9]])
print(f"x: {x.shape}")
print(x)
print(f"\ny: {y.shape}")
print(y)

print(x+y)

# np.dot(x,y) #차원 안맞아서 안

print(np.dot(x.T, y))

print((x.T).dot(y))

#inverse: np.linalg.inv
X = np.array([[1,2,3], [1,0,0], [0,0,1]])
X_inverse = np.linalg.inv(X)

print("X: \n", X)
print("\n inverse of X:\n", X_inverse)

"""## Pandas DataFrame"""

import pandas as pd

# dictionary -> dataframe
data = {
    'year': [2022, 2023, 2024],
    'GDP rate': [2.8, 3.1, 3.0],
    'GDP' : ['1.63M', '1.73M', '1.83M']
    }
df = pd.DataFrame(data)
df.head()

# numpy array -> dataframe
data = np.array([[1,2,3], [4,5,6]])

df = pd.DataFrame(data, columns = ["a", "b", "c"])
df.head()

df = pd.DataFrame(data.T,columns = ['a', 'b'])
df.head()

# csv file -> dataframe
df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/ISLR/Carseats.csv")
df.head()

"""## Handling DataFrames"""

print(df.info())

df.head(10) #first 10 rows

df.tail(5) #last 5 rows

# access specific columns
df["Sales"] #df.Sales
df[["Sales", "US"]].head()

df.describe() # 숫자형 데이터에 대한 분석

"""## 1. Linear Regression
- $\beta = (X^T X)^{-1} X^T Y$
"""

advertising = pd.read_csv("https://www.statlearning.com/s/Advertising.csv", usecols=[1,2,3,4])
advertising.head()

advertising.info()

advertising.describe()

# TV ads and Sales
sns.scatterplot(x=advertising.TV, y = advertising.sales)
plt.show()

class LinearRegression:
  def __init__(self):
    self.weights = None
    self.bias = None

  def fit(self,X,y):
    #Add a column of ones to X for the intercept(bias) term
    X = np.hstack((np.ones((X.shape[0], 1)), X))

    # Calculate weights using the least squares method (closed form solution)
    self.weights = np.linalg.inv((X.T.dot(X))).dot(X.T).dot(y)

    # Extract bias from weights
    self.bias = self.weights[0]
    self.weights = self.weights[1:]

  def predict(self, X):
    # Add a column of ones to X for the intercept term
    X = np.hstack((np.ones((X.shape[0], 1)), X))

    # Predict using the linear regression model
    y_pred = X.dot(np.hstack((self.bias, self.weights)))

    return y_pred

def train_test_split(dataframe, test_size=0.2, random_state=None):
  if random_state:
    np.random.seed(random_state)

  # Shuffle the indices of the dataframe
  indices = np.random.permutation(len(dataframe))

  # Calculate the number of samples in the test set
  test_samples = int(len(dataframe) * test_size)

  # Split indices into train and test indices
  test_indices = indices[:test_samples]
  train_indices = indices[test_samples:]

  # Split dataframe into train and test sets using the indices
  train_data = dataframe.iloc[train_indices]
  test_data = dataframe.iloc[test_indices]

  return train_data, test_data

def mean_squared_error(y_true, y_pred):
  # Calculate squared errors
  squared_errors = [(y_true[i] - y_pred[i]) ** 2 for i in range(len(y_true))]

  # Calculate mean squared error
  mse = sum(squared_errors) / len(y_true)

  return mse

def r_squared(y_true, y_pred):
  # Calculate the mean of the true values
  mean_y_true = sum(y_true) / len(y_true)

  # Calculate the total sum of squares (TSS)
  tss = sum([(y - mean_y_true) ** 2 for y in y_true])

  # Calculate the residual sum of squares (RSS)
  rss = sum([(y_true[i] - y_pred[i]) ** 2 for i in range(len(y_true))])

  # Calculate R-squared
  r2 = 1 - (rss / tss)

  return r2

train_data, test_data = train_test_split(advertising)

X_train, y_train = np.array(train_data.TV).reshape(-1,1), np.array(train_data.sales)
X_test, y_test = np.array(test_data.TV).reshape(-1, 1), np.array(test_data.sales)

# Initialize and fit linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

y_pred = model.predict(X_train)
print("MSE: ", mean_squared_error(y_test, predictions))
print("R-squared: ", r_squared(y_test, predictions))

plt.scatter(X_test, y_test, color = 'blue', label = 'Data') # Scatter plot
plt.plot(X_test, predictions, color = 'red', label = 'Regression Line') # Regression line

for i in range(len(X_test)):
  plt.plot([X_test[i], X_test[i]], [y_test[i], predictions[i]], color = 'gray', linestyle='--', linewidth=0.5)

plt.xlabel('TV')
plt.ylabel('Sales')
plt.title('Scatter plot with Regression Line')
plt.legend()
plt.grid(False)
plt.show()

"""## Multiple linear regression
$sales = \beta_0 + \beta_1 \times TV + \beta_2 \times Radio + \beta_3 \times Newspaper$
"""

X_train, y_train = np.array(train_data.drop("sales", axis=1)), np.array(train_data.sales)
X_test, y_test = np.array(test_data.drop("sales", axis=1)), np.array(test_data.sales)

model = LinearRegression()
model.fit(X_train, y_train)

# Predictions
predictions = model.predict(X_test)

y_pred = model.predict(X_train)
print("MSE: ", mean_squared_error(y_test, predictions))
print("r-squared: ", r_squared(y_test, predictions))

"""## 2. Feature Selection"""

df = pd.read_csv("https://vincentarelbundock.github.io/Rdatasets/csv/MASS/Boston.csv")
df = df.drop("rownames", axis=1)
df.head()

train_data, test_data = train_test_split(df)

X_train, y_train = np.array(train_data.drop("crim", axis=1)), np.array(train_data["crim"])
X_test, y_test = np.array(test_data.drop("crim", axis=1)), np.array(test_data["crim"])

"""## 2-1. Subset Selection"""

def adjusted_r_squared(y_true, y_pred, n_features):
  # Calculate R-squared
  r2 = r_squared(y_true, y_pred)

  # Calculate the number of samples
  n_samples = len(y_true)

  # Calculate adjusted R-squared
  adj_r2 = 1 - ((1 - r2) * (n_samples - 1) / (n_samples - n_features - 1))

  return adj_r2

def subset_selection(X, y, metric):
  n_features = X.shape[1]
  best_subset = []
  best_metric = 0

  for k in range(1, n_features + 1):
    # Generate all possible combinations of features
    subsets = np.array(list(itertools.combinations(range(n_features), k)))

    for subset in subsets:
      # Fit linear regression model using the current subset
      X_subset = X[:, subset]
      model = LinearRegression()
      model.fit(X_subset, y)

      # Make predictions
      y_pred = model.predict(X_subset)
      if metric == "r2":
        metric_val = r_squared(y, y_pred)
      elif metric == "adj_r2":
        metric_val = adjusted_r_squared(y, y_pred, k)

      # Update best subset
      if metric_val > best_metric:
        best_metric = metric_val
        best_subset = subset

  return best_subset

# metric: r-squared
best_subset_indices = subset_selection(X_train, y_train, "r2")
print(f"best subset features: {len(best_subset_indices)} / {len(df.columns) - 1}")
print(list(df.drop(["crim"], axis=1).columns[best_subset_indices]))

# metric: adjusted r-squared
best_subset_indices = subset_selection(X_train, y_train, "adj_r2")
print(f"best subset features: {len(best_subset_indices)} / {len(df.columns) - 1}")
print(list(df.drop(["crim"], axis=1).columns[best_subset_indices]))

"""## 2-2.Forward Step-wise Selection"""

def forward_stepwise_selection(X, y, k_fold=5):
    n_features = X.shape[1]
    selected_features = []
    remaining_features = list(range(n_features))
    best_mse = float('inf')

    for _ in reversed(range(n_features)):
        best_feature = None
        best_mse_with_feature = float('inf')

        # Iterate over remaining features
        for feature in remaining_features:
            # Append the selected feature to the current subset
            current_subset = selected_features + [feature]

            # Perform k-fold cross-validation
            mse_sum = 0
            fold_indices = np.array_split(np.random.permutation(len(X)), k_fold)
            for fold_idx in range(k_fold):
                # Split data into train and validation sets
                val_indices = fold_indices[fold_idx]
                train_indices = np.concatenate([fold_indices[i] for i in range(k_fold) if i != fold_idx])
                X_cross_train, X_cross_val = X[train_indices], X[val_indices]
                y_cross_train, y_cross_val = y[train_indices], y[val_indices]

                # Fit linear regression model using the current subset on the training data
                X_cross_train_subset = X_cross_train[:, current_subset]
                X_cross_val_subset = X_cross_val[:, current_subset]
                model = LinearRegression()
                model.fit(X_cross_train_subset, y_cross_train)

                y_pred = model.predict(X_cross_val_subset)

                # Calculate mean squared error (MSE) for this fold
                mse_fold = mean_squared_error(y_cross_val, y_pred)
                mse_sum += mse_fold

            # Calculate average MSE across all folds for this feature
            avg_mse_with_feature = mse_sum / k_fold

            # Update best feature if average MSE is minimized
            if avg_mse_with_feature < best_mse_with_feature:
                best_mse_with_feature = avg_mse_with_feature
                best_feature = feature

        # Update selected features and remaining features
        selected_features.append(best_feature)
        remaining_features.remove(best_feature)

        # Update best MSE if MSE with the current subset is minimized
        if best_mse_with_feature < best_mse:
            best_mse = best_mse_with_feature
        else:
            break

    return selected_features

best_subset_indices = forward_stepwise_selection(X_train, y_train, 5)
print(f'best subset features: {len(best_subset_indices)} / {len(df.columns) - 1}')
print(list(df.drop(['crim'], axis=1).columns[best_subset_indices]))

"""# 3. Logistic Regression"""

df = pd.read_csv("https://raw.githubusercontent.com/LukeMoraglia/ISLR_datasets/master/data/Default.csv")
df.head()

print(df.default.unique())
print(df.student.unique())

df['student'] = df.student.map({'No': -1, 'Yes': 1})
df['default'] = df.default.map({'No': -1, 'Yes': 1})

train_data, test_data = train_test_split(df)

X_train, y_train = np.array(train_data.drop("default", axis=1)), np.array(train_data.default)
X_test, y_test = np.array(test_data.drop("default", axis=1)), np.array(test_data.default)

class LogisticRegression:
    def __init__(self, learning_rate=0.01, n_iterations=1000):
        self.learning_rate = learning_rate
        self.n_iterations = n_iterations
        self.weights = None
        self.bias = None

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self.weights = np.zeros(n_features)
        self.bias = 0

        for _ in range(self.n_iterations):
            linear_model = np.dot(X, self.weights) + self.bias
            y_predicted = self.sigmoid(linear_model)

            # Gradient descent
            dw = (1 / n_samples) * np.dot(X.T, (y_predicted - y))
            db = (1 / n_samples) * np.sum(y_predicted - y)

            ###### your code here ######
            self.weights -= dw * self.learning_rate
            self.bias -= db * self.learning_rate
            ###### your code here ######

    def predict(self, X):
        linear_model = np.dot(X, self.weights) + self.bias
        y_predicted = self.sigmoid(linear_model)
        ###### your code here ######
        # y_predicted_cls = [1 if y > 0.5 else -1 for y in y_predicted]
        y_predicted_cls = np.where(y_predicted > 0.5, 1, -1)
        ###### your code here ######
        return np.array(y_predicted_cls)

def accuracy(y_true, y_pred):
    # Compute accuracy
    correct = sum(1 for true, pred in zip(y_true, y_pred) if true == pred)
    return correct / len(y_true)

model = LogisticRegression(learning_rate=0.01, n_iterations=1000)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

print("Accuracy: ", accuracy(y_test, y_pred))

"""# 4. Linear Discriminant Analysis (LDA)"""

from sklearn import datasets

iris = datasets.load_iris()
X = iris.data
y = iris.target
label_dict = {0: 'Setosa', 1: 'Versicolor', 2: 'Virginica'}

print(X.shape, y.shape)

"""Recall discriminant score for each class k is:

$$\delta_k(x) = \frac{\mu_k}{\sigma^2}x - \frac{\mu_k^2}{2\sigma^2} + \log \alpha_k$$
"""

n_classes = len(np.unique(y))
n_features = X.shape[1]

# mean vectors for each class
mean_vectors = np.array([X[y == k].mean(axis=0) for k in range(n_classes)])

# shared variance (assumed equal across classes)
S_W = np.zeros((n_features, n_features))
for k in range(n_classes):
    class_scatter = np.cov(X[y == k], rowvar=False, bias=True)
    S_W += class_scatter

# average variance across all classes
shared_variance = np.mean(np.diag(S_W))

# prior probabilities for each class
class_priors = np.array([np.mean(y == k) for k in range(n_classes)])

# discriminant function
def discriminant_function(x):
    discriminant_scores = (mean_vectors.dot(x.T)) / shared_variance \
                        - (np.sum(mean_vectors**2, axis=1) / (2 * shared_variance)) \
                        + np.log(class_priors)
    return np.argmax(discriminant_scores)

predictions = np.apply_along_axis(discriminant_function, 1, X)  # apply to each row (sample)

accuracy = np.mean(predictions == y)
print(f'Accuracy: {accuracy}')
